name: schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */15 * *'

env:
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}

jobs:
  Run-Schedule:
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        run: echo $EMAIL_USER
      - name: echo env2
        run : echo $EMAIL_PASS
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: install dependencies
        run: yarn install
      - name: install playwright
        run: npx playwright install-deps chromium
      - name: run automation
        run: yarn ci
      - name: git setup user.email
        run: git config user.email "automated@noreplay.com"
      - name: git setup user.name
        run: git config user.name "Automated Commit"
      - name: add changes
        run: git add .
      - name: commit changes
        run: git commit -m "Automated commit by schedule"
      - name: push changes
        run: git push origin main -f
